### PR TITLE
Move haret into it's own directory

### PR DESCRIPTION
**Pull request by erickt**
This switches over to use Cargo workspaces to share the same `Cargo.lock` and `target` directory to speed up compilation.

### CODE REVIEW

**Comment by andrewjstone** [comment]
Wow, I didn't even know workspaces existed. They somehow slipped past my radar. For those playing along at home: https://doc.rust-lang.org/beta/book/second-edition/ch14-03-cargo-workspaces.html

Looks like my merge of your other branch added conflicts here. Once those are fixed I'll merge away.

**Comment by erickt** [comment]
@andrewjstone yeah I just learned about em too. Glad to save some time compiling haret a few times. I was a tad concerned about this refactoring slowing down your development process :)

**Comment by erickt** [comment]
Oh and it should be fixed with what I just pushed up.

**Comment by andrewjstone** [comment]
Thanks again! Yay for shaving time of compilation.

**Pull request merged**
