### PR TITLE
add concrete change description

### PR DESCRIPTION
**Pull request by evanmcc**
This PR adds a section to the RFC to clarify in grinding, didactic detail all of the changes that need to be made to the protocol and state machine in order to implement the feature as described.  I tried to keep it abstract and implementation neutral, but you many want to add details specific to haret since it's your RFC.

### CODE REVIEW

**Comment by evanmcc** [comment]
https://github.com/evanmcc/vrrm/pull/11 is my PR doing this work on my erlang version of VR-R.

**Comment by evanmcc** [comment]
sloppy of me, they aren't in vrrm either.

**Comment by andrewjstone** [comment]
I've had to run search/replace about fifty times in the last week for the same thing, so I understand completely.

**Comment by andrewjstone** [comment]
@evanmcc when you get a chance, please do the search replace so I can get this merged in. 
Thanks.

**Comment by evanmcc** [comment]
hilariously I did this about 45 seconds after you asked for it, then neglected to commit or push it :man_facepalming:

**Comment by andrewjstone** [comment]
Thanks!

**Pull request merged**
