### PR TITLE
Change configuration file format

### LINKED ISSUE #76: Convert JSON config to TOML
JSON is a terrible config format primarily because it doesn't have comments. Additionally TOML seems to be standard in rust.

### PR DESCRIPTION
**Pull request by jrgarcia**
Change configuration format to use TOML instead of JSON. This change
updates the documentation, the configuration code, and the Cargo files.

Closes #76

### CODE REVIEW

**Comment by jrgarcia** [comment]
I'm pretty sure I did this correctly. I tested it and with the admin, `config` reports the correct configuration settings. I tested running three nodes and joining them to the same cluster. It worked just fine and the `cluster status` reported everything correctly. Still worth testing pretty rigorously though.

**Comment by andrewjstone** [comment]
Wow @jrgarcia you are my hero :) I'll give this a thorough review a bit later today.

**Comment by jrgarcia** [comment]
Don't get too excited until you're sure it works! 🙂

**Comment by andrewjstone** [comment]
LGTM. Nice work @jrgarcia. Thanks again.

**Pull request merged**
