### PR TITLE
Add RFC #2 for View Change Optimizations

### PR DESCRIPTION
**Pull request by andrewjstone**
[Rendered](https://github.com/vmware/haret/blob/5951f58dac9cb53130bade41736848366eeebe9e/rfcs/2-view-change-optimizations-track-commit-num.md)

Thanks to @evanmcc for the idea.

### CODE REVIEW

**Comment by evanmcc** [comment]
+1, I think that this improves upon my handwavy suggestion quite a lot.

**Comment by justinsheehy** [comment]
+1, I dig this.

**Comment by tsantero** [comment]
+1, the 8 byte overhead per node per `prepare` message is negligible to the cost of a full state transfer from each replica during failure recovery--especially considering that on contended networks  the paper's specified recovery protocol could cause further disruption given a log with a significant number of entries.

**Comment by andrewjstone** [comment]
Thanks @evanmcc @justinsheehy @tsantero. I appreciate you taking the time to read this. Approval from legendary ex-bashos just earned this a merge.

**Pull request merged**
